 version: '3.7'
 networks:
  network:
    driver: bridge
 services:
  dashboard:
    build: 
      context: ./
    container_name: ${PROJECT_NAME}_dashboard
    hostname: ${PROJECT_NAME}_dashboard
    restart: always
    ports:
      - 5000:80
    networks:
      - network